name: flutter_devstat
description: A CLI tool to analyze Flutter project structure and annotate Dart files with their lib/ paths.
version: 1.3.0
homepage: https://bxamra.github.io/
repository: https://github.com/bxamra/flutter_devstat
issue_tracker: https://github.com/bxamra/flutter_devstat/issues
license: MIT

environment:
  sdk: ^3.9.0

# Defines the command-line executable available after global activation
executables:
  flutter_devstat: flutter_devstat

dependencies:
  path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
