name: flutter_devstat
description: >
  A Flutter project structure analyzer and file path annotator.
  It helps you maintain well-organized Flutter projects by showing directory trees,
  adding path headers to Dart files, and updating them automatically.
version: 1.3.0
homepage: https://bxamra.github.io/
repository: https://github.com/bxamra/flutter_devstat
issue_tracker: https://github.com/bxamra/flutter_devstat/issues

environment:
  sdk: ^3.9.0

# Defines the command-line executable available after global activation
executables:
  flutter_devstat: flutter_devstat

dependencies:
  path: ^1.9.0

dev_dependencies:
  lints: ^6.0.0
  test: ^1.26.3
